#!/bin/sh -eux

cd "$(dirname "$0")"

./node_modules/.bin/concurrently --kill-others \
  -n public,functions \
  -c cyan,yellow\
  "cd ../public && yarn run dev" \
  'cd ../functions && yarn run serve'
